config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
    as :user do
   	get "/signup" => "devise/registrations#new"
   	post "signup" => "devise/registrations#create"
    get "/login" => "devise/sessions#new"
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
  end
  resources :users
  resources :posts
  mount Commontator::Engine => '/commontator'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_commontable dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader	
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 250}
  validates :title, presence: true, length: {maximum: 150}
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :validatable
  validates :username, presence: true, uniqueness: true
  has_many :posts, dependent: :destroy
  acts_as_commontator
  def self.find_for_database_authentication(conditions={})
  	find_by(username: conditions[:email]) || find_by(email: conditions[:email])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only:[:edit, :update, :destroy]
	def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
    	flash[:danger] = "Failed!"
    end
  end

  def destroy
  	@post = Post.find(params[:id])
  	if @post.destroy
  		redirect_to root_url
  		flash[:success] = "Post deleted!"
  	end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update_attributes(post_params)
  		flash[:success] = "Edited successful!"
  		redirect_to root_url
  	else
  		render 'edit'
  	end
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :picture)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to(root_url) unless current_user == @post.user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		@users = User.all
		@post = current_user.posts.build if signed_in?
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
  end

  # POST /resource
  def create
  end

  # GET /resource/edit
  def edit
  end

  # PUT /resource
  def update
  end

  # DELETE /resource
  def destroy
  end

  
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
  end

  # POST /resource/sign_in
  def create
  end

  def destroy
  end


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :destroy]

  def index
    @users = User.all
  end

	def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def destroy
	  User.find(params[:id]).destroy
	  redirect_to root_url
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
	  @user = User.find(params[:id])
	  	if @user.update_attributes(user_params)
	      redirect_to root_url
	    else
	      render 'edit'
	    end
  end

  private

  def user_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commontator/comments/_form.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   #
   # Optionally, they can also supply the following variables:
   per_page ||= nil
   thread ||= nil
   no_remote ||= false
%>

<% config = comment.thread.config %>

<% if comment.errors.any? %>
  <div class="comment_error_explanation">
    <h3><%= t "commontator.comment.errors.#{comment.id.blank? ? 'create' : 'update'}" %></h3>

    <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([commontator, thread, comment],
             remote: !no_remote) do |f| %>

  <%= hidden_field_tag :per_page, per_page %>
  
  <div class="comment_form_field">
    <%= f.text_area :body, rows: '7',class: 'form-control' %>
    <%= javascript_tag('Commontator.initMentions()') if Commontator.mentions_enabled %>
  </div>
  
  <div class="comment_form_actions">
    <%= f.submit t("commontator.comment.actions.#{comment.id.blank? ? 'create' : 'update'}"),class: "btn btn-success"%>
    <%= f.submit t('commontator.comment.actions.cancel'), name: 'cancel',class: "btn btn-warning" %>
  </div>
  
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails App</a>
    by Nicky
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My Blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "User", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
           <li><%= link_to "Sign up", signup_path %></li>
           <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<span class="user"><%= link_to post.user.username, post.user %></span>
  <span class="title"><%= post.title %></span>
  <span class="content">
  	<%= post.content %><br>
  	<%= image_tag post.picture.url if post.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/edit.html.erb
<div class="row">
		<aside class="col-md-6 col-md-offset-3">
			<h1>Edit Post</h1>
			<section class="post_form">
	      <%= form_for(@post) do |f| %>
	      <%= render "devise/shared/error_messages", resource: @post %>
	        <div class="field">
	          <%= f.label :title, "Title" %>
	            <%= f.text_area :title %>
	            <%= f.label :content, "Content" %>
	            <%= f.text_area :content %>
	        </div>
	          <%= f.submit 'Post', class: "btn btn-primary" %>
	            <span class="picture">
	              <%= f.file_field :picture %>
	            </span>
	      <% end %>
			</section>
		</aside>
	</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
    <ul class="posts">
      <div class="row">
        <div class="col-md-4">
          <section class="user-info">
            <h3><%= current_user.username %></h1>
            <span><%= link_to "view my profile", current_user %></span><br>
            <span><%= pluralize(current_user.posts.count, "post") %></span>
          </section>
          <section class="post_form">
            <%= form_for(@post) do |f| %>
              <div class="field">
                <%= f.label :title, "Title" %>
                <%= f.text_area :title %>

                <%= f.label :content, "Content" %>
                <%= f.text_area :content %>
              </div>
              <%= f.submit 'Post', class: "btn btn-primary" %>
               <span class="picture">
                <%= f.file_field :picture %>
              </span>
            <% end %>
          </section>
        </div>
        <div class="col-md-8">
          <h1>Newsfeed</h1>
          <% @users.each do |user| %>
            <% user.posts.each do |post| %>
              <li id="post-<%= post.id %>">
                <span class="post-option">
                <% if current_user == post.user %>
                <%= link_to 'edit', edit_post_path(post) %>
                <%= link_to "delete", post, method: :delete,
                                             data: { confirm: "You sure?" } %>
                <%end%>
              </span>
              <span class="user"><%= link_to post.user.username, post.user %></span>
              <span class="title"><%= post.title %></span>
              <span class="content">
                <%= post.content %><br>
                <%= image_tag post.picture.url if post.picture? %>
                
              <span class="timestamp">
                Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
                <%= commontator_thread(post) %>

              
            </li>
            <%end%>
           <%end%>
        </div>
      </div>
    </ul>
<%else%>
	<div class="center jumbotron">
	  <h1>Welcome to the My Blog</h1>
	  <h2>
	    Login to post new article or Sign up now !
	  </h2>
	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-warning" %>
	</div>
<%end%>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= render "devise/shared/error_messages", resource: @user %>
  <%= f.label :name %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit 'Save', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<% if user_signed_in? %>
<h1>All Users</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
          </tr>
        </thead>

       <tbody>
        <% @users.each do |user| %>
         <tr>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to "Delete", user, method: :delete,
                                           data: { confirm: "You sure?" } %><td>
         <% end %>
        </tr>
       </tbody>
      </table>
  </div>
</div>
<%end%>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  		<% if @user.posts.any? %>
				<h3>Posts(<%=@user.posts.count%>)</h3>
				<ol class='posts'>
					<%= render @posts %>
				</ol>
			<% end %>
		</div>
</div>